### ISSUE TITLE
Crash in 1.19.2

### ISSUE THREAD

**Issue by zhenlige** [SHsuperCM/CITResewn#189]
This mod cannot run in 1.19.2.
Error:
```
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod citresewn
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439)
	... 3 more
```

**Comment by SHsuperCM** [comment]
Works fine for me. Gonna need the full logs.
