### ISSUE TITLE
CITResewn crashed.  why

### ISSUE THREAD

**Issue by Rainbowdude5000** [SHsuperCM/CITResewn#324]
Heres the error message:

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of com.formdev.flatlaf.ui.FlatProgressBarUI failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of com.formdev.flatlaf.ui.FlatProgressBarUI failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.desktop/javax.swing.SwingUtilities.loadSystemClass(SwingUtilities.java:2036)
	at java.desktop/javax.swing.UIDefaults.getUIClass(UIDefaults.java:719)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:789)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1073)
	at java.desktop/javax.swing.JProgressBar.updateUI(JProgressBar.java:610)
	at java.desktop/javax.swing.JProgressBar.<init>(JProgressBar.java:339)
	at java.desktop/javax.swing.JProgressBar.<init>(JProgressBar.java:306)
	at io.github.gaming32.modloadingscreen.ActualLoadingScreen.beforeEntrypointType(ActualLoadingScreen.java:177)
	at io.github.gaming32.modloadingscreen.ActualLoadingScreen.beforeEntrypointType(ActualLoadingScreen.java:164)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	... 2 more
Caused by: java.lang.ExceptionInInitializerError
	at shcm.shsupercm.fabric.citresewn.config.CITResewnMixinConfiguration.onLoad(CITResewnMixinConfiguration.java:34)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:709)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 20 more
Caused by: java.lang.RuntimeException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at shcm.shsupercm.fabric.citresewn.config.CITResewnConfig.read(CITResewnConfig.java:62)
	at shcm.shsupercm.fabric.citresewn.config.CITResewnConfig.<clinit>(CITResewnConfig.java:46)
	... 30 more
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:395)
	at com.google.gson.Gson.fromJson(Gson.java:1214)
	at com.google.gson.Gson.fromJson(Gson.java:1124)
	at com.google.gson.Gson.fromJson(Gson.java:1062)
	at shcm.shsupercm.fabric.citresewn.config.CITResewnConfig.read(CITResewnConfig.java:59)
	... 31 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:384)
	... 35 more

**Comment by SHsuperCM** [comment]
Could you send your config file `minecraft/config/citresewn.json`?
