### ISSUE TITLE
modpack crashes with this mod

### ISSUE THREAD

**Issue by camcords** [SHsuperCM/CITResewn#357]
added this to the fabulously optimized modpack cause i wanted to use CITs. it immediately crashed and i don't know why. here's the crash report:

[23:19:37] [Render thread/ERROR]:
 Mixin apply for mod citresewn-defaults failed citresewn-defaults.mixins.json:types.enchantment.BufferBuilderStorageAccessor from mod citresewn-defaults -> net.minecraft.class_4599: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching field_20957:Ljava/util/SortedMap; in net/minecraft/class_4599 for citresewn-defaults.mixins.json:types.enchantment.BufferBuilderStorageAccessor from mod citresewn-defaults->@Accessor[FIELD_GETTER]::getEntityBuilders()Ljava/util/SortedMap; [INJECT Applicator Phase -> citresewn-defaults.mixins.json:types.enchantment.BufferBuilderStorageAccessor from mod citresewn-defaults -> Apply Accessors ->  -> Locate -> citresewn-defaults.mixins.json:types.enchantment.BufferBuilderStorageAccessor from mod citresewn-defaults->@Accessor[FIELD_GETTER]::getEntityBuilders()Ljava/util/SortedMap;]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching field_20957:Ljava/util/SortedMap; in net/minecraft/class_4599 for citresewn-defaults.mixins.json:types.enchantment.BufferBuilderStorageAccessor from mod citresewn-defaults->@Accessor[FIELD_GETTER]::getEntityBuilders()Ljava/util/SortedMap; [INJECT Applicator Phase -> citresewn-defaults.mixins.json:types.enchantment.BufferBuilderStorageAccessor from mod citresewn-defaults -> Apply Accessors ->  -> Locate -> citresewn-defaults.mixins.json:types.enchantment.BufferBuilderStorageAccessor from mod citresewn-defaults->@Accessor[FIELD_GETTER]::getEntityBuilders()Ljava/util/SortedMap;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:519) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:502) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:476) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1411) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1071) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.0.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_310.<init>(class_310.java:601) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[1.20.4-0.15.0.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.0.jar:?]

**Comment by SHsuperCM** [comment]
Show the entite logs
