### ISSUE TITLE
Rendering Entity In World Crash

### ISSUE THREAD

**Issue by the-n1n** [SHsuperCM/CITResewn#390]
When reloading resources this crash occasionally occurs as well as resource pack "failing to load"
```---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-04-04 01:51:14
Description: Rendering entity in world

java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at shcm.shsupercm.fabric.citresewn.defaults.cit.types.TypeEnchantment$Container.getRealTimeCIT(TypeEnchantment.java:228)
	at shcm.shsupercm.fabric.citresewn.cit.CITCache$MultiList.get(CITCache.java:96)
	at shcm.shsupercm.fabric.citresewn.defaults.cit.types.TypeEnchantment$Container.setContext(TypeEnchantment.java:204)
	at net.minecraft.class_970.handler$zgn000$citresewn-defaults$citresewn$enchantment$setAppliedContextAndStartApplyingArmor(class_970.java:1522)
	at net.minecraft.class_970.method_4169(class_970.java)
	at net.minecraft.class_970.method_17157(class_970.java:45)
	at net.minecraft.class_970.method_4199(class_970.java:27)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_922.method_3936(class_922.java:29)
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)```
	
	```Caught error loading resourcepacks!
java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1313)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1280)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractMap.put(AbstractMap.java:209)
	at shcm.shsupercm.fabric.citresewn.defaults.cit.types.TypeEnchantment$Container.load(TypeEnchantment.java:147)
	at shcm.shsupercm.fabric.citresewn.api.CITTypeContainer.loadUntyped(CITTypeContainer.java:65)
	at shcm.shsupercm.fabric.citresewn.cit.ActiveCITs.load(ActiveCITs.java:102)
	at net.minecraft.class_1088.handler$zgb000$citresewn$loadCITs(class_1088.java:546)
	at net.minecraft.class_1088.<init>(class_1088.java:154)
	at net.minecraft.class_1092.method_45884(class_1092.java:87)
	at net.minecraft.class_1092.md3dbd38$fabric-model-loading-api-v1$lambda$loadModelPluginData$0$2(class_1092.java:2079)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1311)
	... 7 more```

**Comment by SHsuperCM** [comment]
Please send the entire log, I cannot reproduce this crash.

**Comment by the-n1n** [comment]
[crash-2024-04-05_02.50.25-client.txt](https://github.com/SHsuperCM/CITResewn/files/14892677/crash-2024-04-05_02.50.25-client.txt)

**Comment by SHsuperCM** [comment]
Not the crash log, the `latest.log` associated with the crash.

**Comment by the-n1n** [comment]
[2024-04-05-1.log](https://github.com/SHsuperCM/CITResewn/files/14892686/2024-04-05-1.log)
Here is the log, Main two errors are at the bottom.

**Comment by SHsuperCM** [comment]
I'm hoping fa7e4b7 fixed this, check again when the next version releases. 
If it doesnt, let me know and I'll reopen the issue.

**Comment by Brancieq-Paul** [comment]
Hi ! Will we have an update in 1.20.1 for this fix ?

**Comment by SHsuperCM** [comment]
> Hi ! Will we have an update in 1.20.1 for this fix ?

Yes, plan is to support 1.20.1 to 1.21.x with all nearby future releases. If I have more time after that, I also want to have 1.19.2 supported.
This bugfix is planned for 1.20.1 as well.
