### ISSUE TITLE
Cit + emf/etf

### ISSUE THREAD

**Issue by TogoLonghole** [SHsuperCM/CITResewn#398]
Crashes when custom items are placed on item stands and using the emf/etf mods alongside citresewn

**Comment by dbrighthd** [comment]
This doesn't happen with me, what versions of those are you using
![image](https://github.com/SHsuperCM/CITResewn/assets/68525639/d2fc47de-c749-4ee3-978b-5d99b38a5734)

**Comment by TogoLonghole** [comment]
![image](https://github.com/SHsuperCM/CITResewn/assets/168941812/fe9ebf36-cc16-4107-943e-d5f186496064)
![image](https://github.com/SHsuperCM/CITResewn/assets/168941812/cd7e6a75-d854-4a92-a3e3-be298886deb0)

**Comment by TogoLonghole** [comment]
ill try downgrade cit resewn but i think i already tried that, thankyou for the reply

**Comment by TogoLonghole** [comment]
---- Minecraft Crash Report ----

// There are four lights!

Time: 2024-05-06 06:52:45
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.method_12832()" because "id" is null
	at me.pepperbell.continuity.client.resource.ResourceRedirectHandler.redirect(ResourceRedirectHandler.java:65)
	at net.minecraft.class_6861.localvar$zml000$continuity$redirectGetResourceId(class_6861.java:1041)
	at net.minecraft.class_6861.method_14486(class_6861.java)
	at net.minecraft.class_3304.method_14486(class_3304.java:52)
	at traben.entity_texture_features.features.texture_handlers.ETFTexture.setupBlinking(ETFTexture.java:212)
	at traben.entity_texture_features.features.texture_handlers.ETFTexture.<init>(ETFTexture.java:100)
	at traben.entity_texture_features.features.ETFManager.getOrCreateETFTexture(ETFManager.java:282)
	at traben.entity_texture_features.features.ETFManager.getETFTextureNoVariation(ETFManager.java:247)
	at me.jellysquid.mods.sodium.client.render.vertex.buffer.SodiumBufferBuilder.mdd938cd$entity_texture_features$lambda$etf$initETFVertexConsumer$0$0(SodiumBufferBuilder.java:551)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at me.jellysquid.mods.sodium.client.render.vertex.buffer.SodiumBufferBuilder.etf$initETFVertexConsumer(SodiumBufferBuilder.java:551)
	at traben.entity_texture_features.features.ETFRenderContext.insertETFDataIntoVertexConsumer(ETFRenderContext.java:162)
	at net.irisshaders.batchedentityrendering.impl.FullyBufferedMultiBufferSource.handler$bgc002$entity_texture_features$etf$injectIntoGetBufferReturn(FullyBufferedMultiBufferSource.java:541)
	at net.irisshaders.batchedentityrendering.impl.FullyBufferedMultiBufferSource.getBuffer(FullyBufferedMultiBufferSource.java:98)
	at net.minecraft.class_898.mdd938cd$iris$lambda$iris$beginEntityRender$0$0(class_898.java:2557)
	at net.minecraft.class_970.method_23192(class_970.java:118)
	at net.minecraft.class_970.method_4169(class_970.java:75)
	at net.minecraft.class_970.method_17157(class_970.java:42)
	at net.minecraft.class_970.method_4199(class_970.java:27)
	at net.minecraft.class_922.redirect$bbe000$elytra_physics$injectTransformation(class_922.java:1056)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_922.method_3936(class_922.java:29)
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.irisshaders.iris.shadows.ShadowRenderer.renderEntities(ShadowRenderer.java:635)
	at net.irisshaders.iris.shadows.ShadowRenderer.renderShadows(ShadowRenderer.java:504)
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.renderShadows(IrisRenderingPipeline.java:1010)
	at net.minecraft.class_761.handler$cip000$iris$renderTerrainShadows(class_761.java:8052)
	at net.minecraft.class_761.method_22710(class_761.java:1241)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.pepperbell.continuity.client.resource.ResourceRedirectHandler.redirect(ResourceRedirectHandler.java:65)
	at net.minecraft.class_6861.localvar$zml000$continuity$redirectGetResourceId(class_6861.java:1041)
	at net.minecraft.class_6861.method_14486(class_6861.java)
	at net.minecraft.class_3304.method_14486(class_3304.java:52)
	at traben.entity_texture_features.features.texture_handlers.ETFTexture.setupBlinking(ETFTexture.java:212)
	at traben.entity_texture_features.features.texture_handlers.ETFTexture.<init>(ETFTexture.java:100)
	at traben.entity_texture_features.features.ETFManager.getOrCreateETFTexture(ETFManager.java:282)
	at traben.entity_texture_features.features.ETFManager.getETFTextureNoVariation(ETFManager.java:247)
	at me.jellysquid.mods.sodium.client.render.vertex.buffer.SodiumBufferBuilder.mdd938cd$entity_texture_features$lambda$etf$initETFVertexConsumer$0$0(SodiumBufferBuilder.java:551)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at me.jellysquid.mods.sodium.client.render.vertex.buffer.SodiumBufferBuilder.etf$initETFVertexConsumer(SodiumBufferBuilder.java:551)
	at traben.entity_texture_features.features.ETFRenderContext.insertETFDataIntoVertexConsumer(ETFRenderContext.java:162)
	at net.irisshaders.batchedentityrendering.impl.FullyBufferedMultiBufferSource.handler$bgc002$entity_texture_features$etf$injectIntoGetBufferReturn(FullyBufferedMultiBufferSource.java:541)
	at net.irisshaders.batchedentityrendering.impl.FullyBufferedMultiBufferSource.getBuffer(FullyBufferedMultiBufferSource.java:98)
	at net.minecraft.class_898.mdd938cd$iris$lambda$iris$beginEntityRender$0$0(class_898.java:2557)
	at net.minecraft.class_970.method_23192(class_970.java:118)
	at net.minecraft.class_970.method_4169(class_970.java:75)
	at net.minecraft.class_970.method_17157(class_970.java:42)
	at net.minecraft.class_970.method_4199(class_970.java:27)
	at net.minecraft.class_922.redirect$bbe000$elytra_physics$injectTransformation(class_922.java:1056)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_922.method_3936(class_922.java:29)
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.irisshaders.iris.shadows.ShadowRenderer.renderEntities(ShadowRenderer.java:635)
	at net.irisshaders.iris.shadows.ShadowRenderer.renderShadows(ShadowRenderer.java:504)
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.renderShadows(IrisRenderingPipeline.java:1010)
	at net.minecraft.class_761.handler$cip000$iris$renderTerrainShadows(class_761.java:8052)
	at net.minecraft.class_761.method_22710(class_761.java:1241)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

-- Entity being rendered --
Details:
	Entity Type: minecraft:armor_stand (net.minecraft.class_1531)
	Entity ID: 324
	Entity Name: Armour Stand
	Entity's Exact location: 21.50, -60.50, -5.50
	Entity's Block location: World: (21,-61,-6), Section: (at 5,3,10 in 1,-4,-1; chunk contains blocks 16,-64,-16 to 31,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.irisshaders.iris.shadows.ShadowRenderer.renderEntities(ShadowRenderer.java:635)
	at net.irisshaders.iris.shadows.ShadowRenderer.renderShadows(ShadowRenderer.java:504)
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.renderShadows(IrisRenderingPipeline.java:1010)
	at net.minecraft.class_761.handler$cip000$iris$renderTerrainShadows(class_761.java:8052)
	at net.minecraft.class_761.method_22710(class_761.java:1241)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_877@34a79cc6
	Location: -13.97,60.00,17.82 - World: (-14,60,17), Section: (at 2,12,1 in -1,3,1; chunk contains blocks -16,-64,16 to -1,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Rotation: 90.0
	Delta: 0.0
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.invokeRenderEntity(class_761.java)
	at net.irisshaders.iris.shadows.ShadowRenderer.renderEntities(ShadowRenderer.java:635)
	at net.irisshaders.iris.shadows.ShadowRenderer.renderShadows(ShadowRenderer.java:504)
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.renderShadows(IrisRenderingPipeline.java:1010)
	at net.minecraft.class_761.handler$cip000$iris$renderTerrainShadows(class_761.java:8052)
	at net.minecraft.class_761.method_22710(class_761.java:1241)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['TogoLonghole'/516, l='ClientLevel', x=13.97, y=-60.00, z=-17.82]]
	Chunk stats: 4096, 1081
	Level dimension: minecraft:overworld
	Level spawn location: World: (9,-60,47), Section: (at 9,4,15 in 0,-4,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1288337 game time, 1000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, continuity:default, continuity:glass_pane_culling_fix, lambdabettergrass:default, cullleaves:smartleaves, file/Minecunts Textures.zip, file/Minecunts Mobs.zip, file/Better Skeletons.zip, file/Better_Cats_V0.09.zip, file/Better_Dogs_Optimized_Beta_V0.03.zip, file/AllFowl.zip, file/Butterflies - Mrblueyeti.zip, file/Better_Rabbits.zip, file/Amazing Axolotls.zip, file/Beefier Bovine.zip, file/Better Endermen.zip, file/Creeper_Overhaul_RP_RUCompat__1.1.2.zip, file/Hazardous Hoglins.zip, file/Pesky Parrots.zip, file/Porkier Pigs.zip, file/Porkier Piglins.zip, file/Puffier Pandas.zip, file/Sludgy Slimes.zip, file/Better_Sheep_V3.zip, file/formidable-frogs.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1099339848 bytes (1048 MiB) / 1916796928 bytes (1828 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 32
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i9-13900KF
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 24
	Number of logical CPUs: 32
	Graphics card #0 name: NVIDIA GeForce RTX 4090
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2684
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5186
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 40516.77
	Virtual memory used (MB): 22761.74
	Swap memory total (MB): 7936.00
	Swap memory used (MB): 110.39
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.8.1
		ambientenvironment: Ambient Environment 11.0.0.1
		antighost: AntiGhost 1.20-fabric0.83.0-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.2.14
		autorun: AutoRun 0.5.0
		axolotlitemfix: Axolotl Item Fix 1.1.7
		badpackets: Bad Packets 0.4.3
		betteradvancements: Better Advancements 0.3.2.162
		betterf3: BetterF3 7.0.2
		betterthirdperson: Better Third Person 1.9.0
		bookshelf: Bookshelf 20.1.10
		camerautils: Camera Utils 1.20.1-1.0.5
		chat_heads: Chat Heads 0.10.32
		chatanimation: ChatAnimation 1.0.5
		chime: Chime 1.5.0
		citresewn: CIT Resewn 1.1.3+1.20
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.20
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.56
		continuity: Continuity 3.0.0-beta.4+1.20.1
		controllable: Controllable 0.20.2
			io_github_libsdl4j_libsdl4j: libsdl4j 2.26.4-1.2
		controlling: Controlling For Fabric 12.0.2
		cosmetica: Cosmetica 1.2.9
			com_github_cosmetica-cc_cosmeticadotjava: CosmeticaDotJava 1.11.2
			sulphate: Sulfate 1.1.1
		cullleaves: Cull Leaves 3.2.0
		customsplashscreen: Custom Splash Screen 2.1.1
		detailab: Detail Armor Bar 2.6.3+1.20.1-fabric
		disguiseheads: DisguiseHeads 1.0.1-mc1.20
		drippyloadingscreen: Drippy Loading Screen 3.0.2
		easyanvils: Easy Anvils 8.0.2
		easymagic: Easy Magic 8.0.1
		eatinganimationid: Eating Animation 1.20+1.9.61
		elytra_physics: Elytra Physics 2.0
		enchdesc: EnchantmentDescriptions 17.0.14
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			spruceui: SpruceUI 5.0.0+1.20
		entity_model_features: Entity Model Features 2.0.2
		entity_texture_features: Entity Texture Features 6.0.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		equipmentcompare: Equipment Compare 1.3.8
			cardinal-components-base: Cardinal Components API (base) 5.2.0
			cardinal-components-entity: Cardinal Components API (entities) 5.2.0
		fabric-api: Fabric API 0.92.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		fallingleaves: Falling Leaves 1.15.6
		fancymenu: FancyMenu 3.2.0
			com_github_keksuccino_japng: japng 0.5.3
			com_github_rtyley_animated-gif-lib-for-java: animated-gif-lib-for-java animated-gif-lib-1.7
		ferritecore: FerriteCore 6.0.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		framework: Framework 0.6.16
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
		gpumemleakfix: Gpu memory leak fix mod 1.20.1-1.8
		iceberg: Iceberg 1.1.18
		immediatelyfast: ImmediatelyFast 1.2.14+1.20.4
			net_lenni0451_reflect: Reflect 1.3.2
		indium: Indium 1.0.30+mc1.20.4
		interdimensional-map-markers: Interdimensional Map Markers 1.0.2
		iris: Iris 1.7.0+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemborders: Item Borders 1.2.2
		java: OpenJDK 64-Bit Server VM 17
		konkrete: Konkrete 1.8.1
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lambdabettergrass: SuperBetterGrass 1.5.2+1.20.1
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
		lazydfu: LazyDFU 0.1.3
		lightoverlay: Light Overlay 8.0.0
		lithium: Lithium 0.11.2
		loadingbackgrounds: Loading Backgrounds 1.3.0
		melody: Melody 1.0.3
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		minimepets: MiniMePets 1.0.1-mc1.20.1
		modelfix: Model Gap Fix 1.15
		modmenu: Mod Menu 7.2.2
		mousetweaks: Mouse Tweaks 2.26
		mousewheelie: Mouse Wheelie 1.13.0+mc1.20.1
			amecsapi: Amecs API 1.5.1+mc1.20-pre1
			coat: Coat 1.0.0-beta.20+mc1.20-pre1
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20-pre1
			tweed4_base: tweed4_base 1.7.1+mc1.20-pre1
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.20-pre1
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.20-pre1
		nonametag: No Name Tag Render 1.0.0
		notenoughanimations: NotEnoughAnimations 1.7.3
		optigui: OptiGUI 2.1.7
			optiglue: OptiGlue 2.1.7-mc.1.19.3
			org_apache_commons_commons-text: commons-text 1.10.0
			org_ini4j_ini4j: ini4j 0.5.4
		panorama_screens: Panorama Screens 1.0+fabric+mc1.20
		panoramica: Panoramica 1.2.1
		ping-wheel: Ping Wheel 1.8.0
		prism: Prism 1.0.5
		puzzle: Puzzle 1.5.2+1.20
			puzzle-base: Puzzle Base 1.5.2+1.20
			puzzle-gui: Puzzle GUI 1.5.2+1.20
			puzzle-models: Puzzle Models 1.5.2+1.20
			puzzle-splashscreen: Puzzle Splash Screen 1.5.2+1.20
		puzzleslib: Puzzles Lib 8.1.18
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		rmh: RemoveMouseoverHighlight 0.0.2+MC1.20(Fabric)
		searchables: Searchables 1.0.3
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		skin-toggle-mod: Skin Toggle Mod 1.6
		skinlayers3d: 3d-Skin-Layers 1.6.4
		slight-gui-modifications: 'Slight' GUI Modifications 2.6.1
			mm: Manningham Mills 2.1
			org_codehaus_groovy_groovy: groovy 3.0.11
			org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.11
		sodium: Sodium 0.5.8+mc1.20.1
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.3.1
		spark: spark 1.10.53
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		starlight: Starlight 1.1.2+fabric.dbc156f
		tooltipfix: ToolTip Fix 1.1.1-1.20
		ukulib: ukulib 0.7.0+1.20
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			gs_mclo_java_mclogs-java: mclogs-java 2.1.1
		ukus-armor-hud: uku's Armor HUD 0.3.10+mc1.20.1
		unionlib: UnionLib 1.20.1-10.2.5-Fabric
		vistas: Vistas 2.5.2
		visuality: Visuality 0.7.1+1.20
		waveycapes: WaveyCapes 1.4.6
		weaponmaster: YDM's Weapon Master 3.0.5
		worldeditcui: WorldEditCUI 1.20+01
		wthit: wthit 8.10.0
		xaerominimap: Xaero's Minimap 24.1.1
		xaeroworldmap: Xaero's World Map 1.38.4
	Loaded Shaderpack: ComplementaryUnbound_r5.1.1.zip
		Profile: Custom (+7 options changed by user)
	Launched Version: fabric-loader-0.15.11-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 4090/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.86, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, continuity:default, continuity:glass_pane_culling_fix, lambdabettergrass:default (incompatible), cullleaves:smartleaves, file/Minecunts Textures.zip, file/Minecunts Mobs.zip, file/Better Skeletons.zip (incompatible), file/Better_Cats_V0.09.zip, file/Better_Dogs_Optimized_Beta_V0.03.zip, file/AllFowl.zip, file/Butterflies - Mrblueyeti.zip (incompatible), file/Better_Rabbits.zip (incompatible), file/Amazing Axolotls.zip (incompatible), file/Beefier Bovine.zip, file/Better Endermen.zip (incompatible), file/Creeper_Overhaul_RP_RUCompat__1.1.2.zip (incompatible), file/Hazardous Hoglins.zip, file/Pesky Parrots.zip (incompatible), file/Porkier Pigs.zip, file/Porkier Piglins.zip, file/Puffier Pandas.zip, file/Sludgy Slimes.zip, file/Better_Sheep_V3.zip, file/formidable-frogs.zip (incompatible)
	Current Language: en_gb
	CPU: 32x 13th Gen Intel(R) Core(TM) i9-13900KF
	Server Running: true
	Player Count: 1 / 8; [class_3222['TogoLonghole'/516, l='ServerLevel[Entity Tester]', x=13.97, y=-60.00, z=-17.82]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by SHsuperCM** [comment]
I need the entire log, not just the crash report. You can upload the file directly instead of pasting its contents.

**Comment by TogoLonghole** [comment]
can you direct me as to where the log is ? i thought thats what it was :D thanks

**Comment by TogoLonghole** [comment]
[latest.log](https://github.com/SHsuperCM/CITResewn/files/15222191/latest.log)

**Comment by TogoLonghole** [comment]
Also i didnt realise i said item stands at the start, its specifically armor stands
