### ISSUE TITLE
Fails to load item

### ISSUE THREAD

**Issue by ninjaguardian** [SHsuperCM/CITResewn#452]
Log:
```java
[14:36:16] [Worker-Main-18/ERROR]: Unknown model loader: forge:obj
[14:36:16] [Worker-Main-18/INFO]: [citresewn] Loading item CIT models...
[14:36:16] [Worker-Main-18/ERROR]: {citresewn} Errored loading model in minecraft:citresewn/cit/crossbow.properties from enchancement_crossbow_fix
[14:36:16] [Worker-Main-18/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "shcm.shsupercm.fabric.citresewn.defaults.mixin.types.item.JsonUnbakedModelAccessor.getTextureMap()" because "itemJson" is null
[14:36:16] [Worker-Main-18/INFO]: [STDERR]: 	at shcm.shsupercm.fabric.citresewn.defaults.cit.types.TypeItem.loadUnbakedAssets(TypeItem.java:158)
[14:36:16] [Worker-Main-18/INFO]: [STDERR]: 	at net.minecraft.class_1088.handler$ddp000$citresewn-defaults$citresewn$addTypeItemModels(class_1088.java:5121)
[14:36:16] [Worker-Main-18/INFO]: [STDERR]: 	at net.minecraft.class_1088.<init>(class_1088.java:196)
[14:36:16] [Worker-Main-18/INFO]: [STDERR]: 	at net.minecraft.class_1092.method_18178(class_1092.java:52)
[14:36:16] [Worker-Main-18/INFO]: [STDERR]: 	at net.minecraft.class_1092.method_18789(class_1092.java:19)
[14:36:16] [Worker-Main-18/INFO]: [STDERR]: 	at net.minecraft.class_4080.method_18791(class_4080.java:11)
[14:36:16] [Worker-Main-18/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[14:36:16] [Worker-Main-18/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[14:36:16] [Worker-Main-18/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[14:36:16] [Worker-Main-18/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[14:36:16] [Worker-Main-18/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[14:36:16] [Worker-Main-18/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[14:36:16] [Worker-Main-18/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

stick.properties:
```properties
type=item
items=crossbow
texture=minecraft:item/stick.png
```

**Comment by ninjaguardian** [comment]
nvm fixed with
```properties
type=item
items=crossbow
model=item/stick
```
